//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGerenciamentoSalao.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caixa
    {
        public int idCaixa { get; set; }
        public double valorTotal { get; set; }
        public double valorSaida { get; set; }
        public double valorEntrada { get; set; }
        public System.DateTime dtFechamento { get; set; }
        public string status { get; set; }
    }
}
