//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGerenciamentoSalao.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corte
    {
        public int idCorte { get; set; }
        public int idFuncionario { get; set; }
        public int idServico { get; set; }
        public double valor { get; set; }
        public Nullable<System.DateTime> dtInclusao { get; set; }
    }
}
