//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGerenciamentoSalao.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemVenda
    {
        public int idItemVenda { get; set; }
        public int idVenda { get; set; }
        public int idProduto { get; set; }
        public double valorProduto { get; set; }
        public double valorDesconto { get; set; }
        public double valorTotal { get; set; }
        public double percDesconto { get; set; }
        public double qntde { get; set; }
        public Nullable<System.DateTime> dtInclusao { get; set; }
    }
}
