//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGerenciamentoSalao.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEventos
    {
        public int idLog { get; set; }
        public string evento { get; set; }
        public string valoranterior { get; set; }
        public string valornovo { get; set; }
        public string usuariodealteracao { get; set; }
        public System.DateTime dataalteracao { get; set; }
    }
}
