//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGerenciamentoSalao.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificaPagamento
    {
        public int idNotificacao { get; set; }
        public double valor { get; set; }
        public string competencia { get; set; }
        public string cdLiberacaoGet { get; set; }
        public string cdLiberacaoSet { get; set; }
        public Nullable<int> vencimento { get; set; }
        public Nullable<int> dialimite { get; set; }
    }
}
