//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGerenciamentoSalao.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int idPeople { get; set; }
        public string name { get; set; }
        public string cpf { get; set; }
        public string city { get; set; }
        public string uf { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
