//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGerenciamentoSalao.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int idService { get; set; }
        public string service1 { get; set; }
        public decimal price { get; set; }
        public string ative { get; set; }
        public string cpfStore { get; set; }
    }
}
