//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIGerenciamentoSalao.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int idVenda { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<double> valorTotal { get; set; }
        public Nullable<double> descontoTotal { get; set; }
        public Nullable<double> percDescTotal { get; set; }
        public Nullable<System.DateTime> dtInclusao { get; set; }
        public string status { get; set; }
        public string tipoPagamento { get; set; }
    }
}
